# Generated by Django 5.0.6 on 2024-05-19 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_options_remove_user_name_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('url', models.URLField()),
                ('poster', models.URLField()),
                ('description', models.CharField()),
                ('rating', models.FloatField(default=1.0)),
                ('datePublished', models.DateField()),
                ('keywords', models.CharField()),
                ('duration', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
