# Generated by Django 5.0.6 on 2024-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_movies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='keywords',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.URLField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url',
            field=models.URLField(default='N/A'),
        ),
    ]
