# Generated by Django 5.0.6 on 2024-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_movies_duration_alter_movies_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='keywords',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
